### YamlMime:ManagedReference
items:
- uid: Vortex.Adapters.Connector.Tc3.OnlineVariableInfo.SymbolLoaderSettings
  commentId: T:Vortex.Adapters.Connector.Tc3.OnlineVariableInfo.SymbolLoaderSettings
  id: OnlineVariableInfo.SymbolLoaderSettings
  parent: Vortex.Adapters.Connector.Tc3
  children: []
  langs:
  - csharp
  - vb
  name: OnlineVariableInfo.SymbolLoaderSettings
  nameWithType: OnlineVariableInfo.SymbolLoaderSettings
  fullName: Vortex.Adapters.Connector.Tc3.OnlineVariableInfo.SymbolLoaderSettings
  type: Class
  source:
    remote:
      path: vortex.connectors/src/connectors/Vortex.Adapters.Connector.Tc3/AdsConnector/Symbols/OnlineVariableInfo.cs
      branch: develop
      repo: http://192.168.0.28/foxtroth.vortex/vortex.base/_git/ivf
    id: SymbolLoaderSettings
    path: ../ivf/vortex.connectors/src/connectors/Vortex.Adapters.Connector.Tc3/AdsConnector/Symbols/OnlineVariableInfo.cs
    startLine: 162
  assemblies:
  - Vortex.Adapters.Connector.Tc3
  namespace: Vortex.Adapters.Connector.Tc3
  syntax:
    content: 'class SymbolLoaderSettings : ISymbolLoaderSettings'
    content.vb: >-
      Class SymbolLoaderSettings

          Implements ISymbolLoaderSettings
  inheritance:
  - System.Object
  implements:
  - TwinCAT.ISymbolLoaderSettings
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - Vortex.Adapters.Connector.Tc3.OnlineVariableInfo.SymbolLoaderSettings.Vortex.Connector.IValueTagExtensions.Cast``1(System.Object)
  modifiers.csharp:
  - class
  modifiers.vb:
  - Class
references:
- uid: Vortex.Adapters.Connector.Tc3
  commentId: N:Vortex.Adapters.Connector.Tc3
  name: Vortex.Adapters.Connector.Tc3
  nameWithType: Vortex.Adapters.Connector.Tc3
  fullName: Vortex.Adapters.Connector.Tc3
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: TwinCAT.ISymbolLoaderSettings
  commentId: T:TwinCAT.ISymbolLoaderSettings
  parent: TwinCAT
  isExternal: true
  name: ISymbolLoaderSettings
  nameWithType: ISymbolLoaderSettings
  fullName: TwinCAT.ISymbolLoaderSettings
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Vortex.Adapters.Connector.Tc3.OnlineVariableInfo.SymbolLoaderSettings.Vortex.Connector.IValueTagExtensions.Cast``1(System.Object)
  commentId: M:Vortex.Connector.IValueTagExtensions.Cast``1(``0,System.Object)
  parent: Vortex.Connector.IValueTagExtensions
  definition: Vortex.Connector.IValueTagExtensions.Cast``1(``0,System.Object)
  name: Cast<OnlineVariableInfo.SymbolLoaderSettings>(Object)
  nameWithType: IValueTagExtensions.Cast<OnlineVariableInfo.SymbolLoaderSettings>(Object)
  fullName: Vortex.Connector.IValueTagExtensions.Cast<Vortex.Adapters.Connector.Tc3.OnlineVariableInfo.SymbolLoaderSettings>(System.Object)
  nameWithType.vb: IValueTagExtensions.Cast(Of OnlineVariableInfo.SymbolLoaderSettings)(Object)
  fullName.vb: Vortex.Connector.IValueTagExtensions.Cast(Of Vortex.Adapters.Connector.Tc3.OnlineVariableInfo.SymbolLoaderSettings)(System.Object)
  name.vb: Cast(Of OnlineVariableInfo.SymbolLoaderSettings)(Object)
  spec.csharp:
  - uid: Vortex.Connector.IValueTagExtensions.Cast``1(System.Object)
    name: Cast<OnlineVariableInfo.SymbolLoaderSettings>
    nameWithType: IValueTagExtensions.Cast<OnlineVariableInfo.SymbolLoaderSettings>
    fullName: Vortex.Connector.IValueTagExtensions.Cast<Vortex.Adapters.Connector.Tc3.OnlineVariableInfo.SymbolLoaderSettings>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Vortex.Connector.IValueTagExtensions.Cast``1(System.Object)
    name: Cast(Of OnlineVariableInfo.SymbolLoaderSettings)
    nameWithType: IValueTagExtensions.Cast(Of OnlineVariableInfo.SymbolLoaderSettings)
    fullName: Vortex.Connector.IValueTagExtensions.Cast(Of Vortex.Adapters.Connector.Tc3.OnlineVariableInfo.SymbolLoaderSettings)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: TwinCAT
  commentId: N:TwinCAT
  isExternal: true
  name: TwinCAT
  nameWithType: TwinCAT
  fullName: TwinCAT
- uid: Vortex.Connector.IValueTagExtensions.Cast``1(``0,System.Object)
  commentId: M:Vortex.Connector.IValueTagExtensions.Cast``1(``0,System.Object)
  isExternal: true
  name: Cast<T>(T, Object)
  nameWithType: IValueTagExtensions.Cast<T>(T, Object)
  fullName: Vortex.Connector.IValueTagExtensions.Cast<T>(T, System.Object)
  nameWithType.vb: IValueTagExtensions.Cast(Of T)(T, Object)
  fullName.vb: Vortex.Connector.IValueTagExtensions.Cast(Of T)(T, System.Object)
  name.vb: Cast(Of T)(T, Object)
  spec.csharp:
  - uid: Vortex.Connector.IValueTagExtensions.Cast``1(``0,System.Object)
    name: Cast<T>
    nameWithType: IValueTagExtensions.Cast<T>
    fullName: Vortex.Connector.IValueTagExtensions.Cast<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Vortex.Connector.IValueTagExtensions.Cast``1(``0,System.Object)
    name: Cast(Of T)
    nameWithType: IValueTagExtensions.Cast(Of T)
    fullName: Vortex.Connector.IValueTagExtensions.Cast(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Vortex.Connector.IValueTagExtensions
  commentId: T:Vortex.Connector.IValueTagExtensions
  parent: Vortex.Connector
  name: IValueTagExtensions
  nameWithType: IValueTagExtensions
  fullName: Vortex.Connector.IValueTagExtensions
- uid: Vortex.Connector
  commentId: N:Vortex.Connector
  name: Vortex.Connector
  nameWithType: Vortex.Connector
  fullName: Vortex.Connector
